import { useEffect, useMemo, useRef, useState, useCallback } from 'react'

// ─── DATA ─────────────────────────────────────────────────────────────────────

const ATTACKS = [
  {
    id: 'credential_stuffing',
    backend: 'credential_stuffing',
    title: 'Credential stuffing',
    severity: 'critical',
    status: 'defended',
    target: 'WebAuthn gate',
    short: 'Leaked roll number and PIN are tried against the vote endpoint.',
    payload: ['roll_no=101', 'pin=1234', 'assertion=null'],
    commands: [
      'load leaked_credentials.csv',
      'try roll_no + pin against /vote/complete',
      'observe WebAuthn challenge failure',
    ],
    defense:
      'Touch ID/WebAuthn requires the enrolled Secure Enclave private key. PIN knowledge alone cannot sign the server challenge.',
    limitation:
      'A stolen PIN can still harm privacy if PIN-derived secrets are weak. Use high-entropy authenticator-derived secrets for a production system.',
    future:
      'Use WebAuthn PRF or platform-keystore secrets so the voting secret is generated by hardware, not memorized by the voter.',
    hasInputs: true,
    animType: 'credential',
  },
  {
    id: 'double_vote',
    backend: 'double_vote',
    title: 'Double vote',
    severity: 'high',
    status: 'defended',
    target: 'votes.nullifier',
    short: 'The same voter attempts to submit a second ballot.',
    payload: ['duplicate nullifier', 'same election id', 'new ciphertext'],
    commands: [
      'select latest nullifier from votes',
      'attempt duplicate insert',
      'expect UNIQUE constraint rejection',
    ],
    defense:
      'The nullifier is stable per voter per election, and the votes table enforces UNIQUE(nullifier).',
    limitation:
      'Old demo voters created before the stable-nullifier migration should be re-registered for a clean demo.',
    future:
      'Add formal election IDs and signed election manifests so nullifier domains cannot be accidentally reused.',
    animType: 'double_vote',
  },
  {
    id: 'fake_shard',
    backend: 'fake_shard',
    title: 'Fake trustee shard',
    severity: 'critical',
    status: 'defended',
    target: 'admin reveal',
    short: 'A malicious trustee submits a corrupted Shamir shard.',
    payload: ['trustee_id=mallory', 'shard=1-deadbeef'],
    commands: [
      'submit forged shard',
      'verify against Feldman commitments',
      'reject before shard store',
    ],
    defense:
      'Feldman VSS commitments reject shards that do not match the key-generation polynomial.',
    limitation:
      'Commitments must be public and independently archived. If only the database stores them, a DB admin is still a trust anchor.',
    future:
      'Publish VSS commitments to an append-only transparency log or blockchain before voting begins.',
    animType: 'fake_shard',
  },
  {
    id: 'merkle_forgery',
    backend: 'merkle_forgery',
    title: 'Merkle root spoof',
    severity: 'medium',
    status: 'defended',
    target: 'receipt verifier',
    short: 'An attacker invents a fake receipt path and fake root.',
    payload: ['fake leaf', 'fake proof path', 'fake root'],
    commands: [
      'generate fake leaf',
      'build attacker-controlled root',
      'compare against /election/root',
    ],
    defense:
      'Receipts verify against the public bulletin-board root, not a root supplied by the attacker.',
    limitation:
      'If the voter checks only inside a compromised browser, an extension could spoof both receipt and root response.',
    future:
      'Mirror roots to independent auditors, signed SMS, newspaper hash, blockchain, or CT-style transparency logs.',
    animType: 'merkle_forgery',
  },
  {
    id: 'panic_pin',
    backend: 'panic_pin',
    title: 'Panic PIN coercion',
    severity: 'medium',
    status: 'defended',
    target: 'duress flow',
    short: 'A coercer watches the voter cast a ballot using a panic PIN.',
    payload: ['pin=panic', 'is_decoy=1', 'normal receipt'],
    commands: [
      'cast with panic PIN',
      'return normal success UI',
      'skip decoy row during reveal',
    ],
    defense:
      'The surface flow stays normal, but final tally skips rows marked is_decoy=1.',
    limitation:
      'Coercion resistance can leak through timing, payload size, or UI differences if the panic path diverges.',
    future:
      'Use constant-size payloads, timing padding, and a revoting model where the last valid vote wins.',
    animType: 'panic_pin',
  },
  {
    id: 'dom_hijack',
    title: 'DOM ballot swap',
    severity: 'critical',
    status: 'partially exposed',
    target: 'browser state',
    short: 'A malicious browser extension changes the selected candidate before encryption.',
    payload: ['content script', 'React state mutation', 'candidate swap'],
    commands: [
      'hook candidate click handler',
      'replace selected candidate before AES-GCM',
      'let user sign altered ciphertext',
    ],
    defense:
      'Ciphertext tampering after encryption fails. WebAuthn binds the signed challenge to the enrolled device.',
    limitation:
      'If malware changes the plaintext before encryption, the backend cannot know the user intended a different candidate.',
    future:
      'Use locked-down kiosk mode, extension-free browser profiles, CSP hardening, and out-of-band candidate confirmation.',
    animType: 'dom_hijack',
  },
  {
    id: 'db_tamper',
    title: 'Database tamper',
    severity: 'high',
    status: 'defended',
    target: 'votes table',
    short: 'A database admin edits ciphertext or Merkle leaves after voting.',
    payload: ['UPDATE votes', 'modified ciphertext', 'root mismatch'],
    commands: [
      'mutate encrypted_vote bytes',
      'recompute detection chain',
      'observe Merkle mismatch',
    ],
    defense:
      'Merkle roots anchor the ledger. Receipt verification fails if DB rows change without a matching public root.',
    limitation:
      'A single-server public board can be rewritten by a fully compromised server unless roots are externally archived.',
    future:
      'Publish roots to independent witnesses, blockchain, or a signed append-only transparency log.',
    animType: 'db_tamper',
  },
]

// ─── CONSTANTS ────────────────────────────────────────────────────────────────

const SEV_COLOR = { critical: '#8a1a1a', high: '#a45b12', medium: '#2a6a3a' }
const STATUS_COLOR = {
  defended: '#8fc8b0',
  'partially exposed': '#c8a951',
  'future work': '#5a8fa8',
  vulnerable: '#ff6b6b',
  needs_data: '#8899aa',
}
const DB_COLS = ['id', 'nullifier', 'aes_key', 'is_decoy', 'merkle_leaf', 'timestamp']

const API_BASE = import.meta.env?.VITE_API_BASE ?? 'http://localhost:8000'

// ─── CANVAS ANIMATION ENGINE ──────────────────────────────────────────────────

function drawBox(ctx, x, y, w, h, bg, stroke, r = 6) {
  ctx.beginPath()
  ctx.roundRect(x, y, w, h, r)
  ctx.fillStyle = bg
  ctx.fill()
  ctx.strokeStyle = stroke
  ctx.lineWidth = 1
  ctx.stroke()
}

function drawLabel(ctx, text, x, y, color = '#d7e2dc', size = 11, align = 'center') {
  ctx.fillStyle = color
  ctx.font = `${size}px monospace`
  ctx.textAlign = align
  ctx.fillText(text, x, y)
}

function arrowH(ctx, x1, y, x2, color = '#8aa1a8') {
  ctx.strokeStyle = color
  ctx.lineWidth = 1.5
  ctx.beginPath()
  ctx.moveTo(x1, y)
  ctx.lineTo(x2, y)
  ctx.stroke()
  ctx.beginPath()
  ctx.moveTo(x2 - 6, y - 4)
  ctx.lineTo(x2, y)
  ctx.lineTo(x2 - 6, y + 4)
  ctx.stroke()
}

// Individual animation functions — each returns a cleanup fn
function animCredential(ctx) {
  let tick = 0
  const id = setInterval(() => {
    const W = ctx.canvas.width, H = ctx.canvas.height
    ctx.clearRect(0, 0, W, H)
    ctx.fillStyle = '#070a0d'
    ctx.fillRect(0, 0, W, H)

    const phase = tick < 12 ? 0 : tick < 24 ? 1 : tick < 36 ? 2 : 3

    drawLabel(ctx, 'LEAKED DB', 60, 20, '#8aa1a8', 9)
    drawLabel(ctx, 'PIN CHECK', 205, 20, '#8aa1a8', 9)
    drawLabel(ctx, 'WEBAUTHN GATE', 365, 20, '#8aa1a8', 9)

    const pinOk = phase >= 1
    drawBox(ctx, 160, 30, 85, 36, pinOk ? '#1a3a1a' : '#1a1a1a', pinOk ? '#8fc8b0' : '#26343a')
    drawLabel(ctx, 'PIN ✓', 202, 52, pinOk ? '#8fc8b0' : '#8aa1a8', 11)

    const waFail = phase >= 3
    const waPulse = phase === 2 && tick % 20 < 10
    const waBg = waFail ? '#8a1a1a' : waPulse ? '#1a2a3a' : '#1a1a1a'
    drawBox(ctx, 300, 30, 130, 36, waBg, waFail ? '#e24b4a' : phase >= 2 ? '#5a8fa8' : '#26343a')
    drawLabel(ctx, waFail ? '401 REJECTED' : 'HARDWARE KEY?', 365, 49, waFail ? '#ff6b6b' : '#8aa1a8', 10)

    drawBox(ctx, 10, 30, 90, 36, '#1a1010', '#8a1a1a')
    drawLabel(ctx, 'roll=101', 55, 45, '#ffb3b3', 10)
    drawLabel(ctx, 'pin=1234', 55, 58, '#ffb3b3', 9)

    arrowH(ctx, 102, 48, 158, '#8fc8b0')
    arrowH(ctx, 247, 48, 298, phase >= 2 ? '#8fc8b0' : '#26343a')

    if (waFail) {
      drawLabel(ctx, 'WebAuthn Assertion Missing', 365, 75, '#ff6b6b', 9)
      for (let i = 0; i < 6; i++) {
        const bx = 300 + (i % 3) * 43, by = 90 + Math.floor(i / 3) * 20
        drawBox(ctx, bx, by, 38, 15, '#1b252a', '#26343a', 3)
        drawLabel(ctx, '\uD83D\uDD12', bx + 19, by + 12, '#5a8fa8', 10)
      }
      drawLabel(ctx, 'HARDWARE WALL (Secure Enclave)', 365, 150, '#5a8fa8', 10)
    }

    tick++
    if (tick > 80) tick = 0
  }, 80)
  return () => clearInterval(id)
}

function animDoubleVote(ctx) {
  let tick = 0
  const id = setInterval(() => {
    const W = ctx.canvas.width, H = ctx.canvas.height
    ctx.clearRect(0, 0, W, H)
    ctx.fillStyle = '#070a0d'
    ctx.fillRect(0, 0, W, H)
    const t = tick

    drawBox(ctx, 30, 10, 420, 24, '#10161a', '#26343a', 4)
    drawLabel(ctx, 'votes table', 240, 26, '#c8a951', 10)

    drawBox(ctx, 30, 44, 420, 28, '#1a2a1a', '#2a4a2a', 4)
    drawLabel(ctx, 'NULLIFIER: 0xb3f4d10a...  [LOCKED]', 240, 62, '#8fc8b0', 10)

    if (t > 8) {
      const enterX = Math.max(30, 460 - (t - 8) * 9)
      const alpha = t > 28 ? Math.max(0, 1 - (t - 28) * 0.07) : 1
      if (alpha > 0) {
        const col = t > 24 ? `rgba(139,26,26,${alpha})` : '#1a1010'
        const str = t > 24 ? `rgba(226,75,74,${alpha})` : '#8a1a1a'
        drawBox(ctx, Math.min(enterX, 452), 82, 420, 28, col, str, 4)
        drawLabel(ctx, 'DUPLICATE: 0xb3f4d10a...', Math.min(enterX + 210, 240 + enterX / 2), 100, `rgba(255,179,179,${alpha})`, 10)
      }
    }

    if (t > 24 && t < 32) {
      ctx.strokeStyle = `rgba(226,75,74,${(32 - t) / 8})`
      ctx.lineWidth = 3
      ctx.beginPath()
      ctx.roundRect(28, 42, 424, 70, 6)
      ctx.stroke()
    }

    if (t > 30) {
      drawBox(ctx, 30, 120, 420, 22, '#10161a', '#c8a951', 4)
      drawLabel(ctx, 'SQLITE_CONSTRAINT: UNIQUE constraint failed: votes.nullifier', 240, 135, '#c8a951', 9)
    }

    tick++
    if (tick > 65) tick = 0
  }, 70)
  return () => clearInterval(id)
}

function animFakeShard(ctx) {
  let tick = 0
  const id = setInterval(() => {
    const W = ctx.canvas.width, H = ctx.canvas.height
    ctx.clearRect(0, 0, W, H)
    ctx.fillStyle = '#070a0d'
    ctx.fillRect(0, 0, W, H)
    const t = tick

    ctx.strokeStyle = '#5a8fa8'
    ctx.lineWidth = 1.5
    ctx.beginPath()
    for (let x = 20; x <= 440; x++) {
      const fx = (x - 230) / 80
      const y = 150 - fx * fx * 28
      x === 20 ? ctx.moveTo(x, y) : ctx.lineTo(x, y)
    }
    ctx.stroke()
    drawLabel(ctx, 'VSS polynomial  (secret)', 230, 168, '#5a8fa8', 9)

    ;[[80, 100], [160, 120], [260, 144], [340, 132], [400, 110]].forEach(([px, py]) => {
      ctx.beginPath()
      ctx.arc(px, py, 5, 0, Math.PI * 2)
      ctx.fillStyle = '#8fc8b0'
      ctx.fill()
      ctx.strokeStyle = '#2a6a3a'
      ctx.lineWidth = 1
      ctx.stroke()
    })

    if (t > 5) {
      ctx.beginPath()
      ctx.arc(310, 55, 6, 0, Math.PI * 2)
      ctx.fillStyle = '#e24b4a'
      ctx.fill()
      ctx.strokeStyle = '#8a1a1a'
      ctx.lineWidth = 1.5
      ctx.stroke()
      drawLabel(ctx, '1-deadbeef (FAKE)', 310, 47, '#ffb3b3', 9)
    }

    if (t > 10 && t < 45) {
      const angle = ((t - 10) / 35) * Math.PI * 2
      ctx.save()
      ctx.translate(230, 100)
      ctx.beginPath()
      ctx.moveTo(0, 0)
      ctx.arc(0, 0, 200, angle - 0.3, angle, false)
      ctx.closePath()
      ctx.fillStyle = 'rgba(90,143,168,0.08)'
      ctx.fill()
      ctx.restore()
    }

    if (t > 40) {
      ctx.strokeStyle = '#e24b4a'
      ctx.lineWidth = 2
      ctx.beginPath(); ctx.moveTo(303, 48); ctx.lineTo(317, 62); ctx.stroke()
      ctx.beginPath(); ctx.moveTo(317, 48); ctx.lineTo(303, 62); ctx.stroke()
      drawLabel(ctx, 'g^y ≠ Π(g^aᵢ)^xⁱ  →  SHARD REJECTED', 230, 22, '#e24b4a', 10)
    }

    tick++
    if (tick > 70) tick = 0
  }, 70)
  return () => clearInterval(id)
}

function animMerkle(ctx) {
  let tick = 0
  const id = setInterval(() => {
    const W = ctx.canvas.width, H = ctx.canvas.height
    ctx.clearRect(0, 0, W, H)
    ctx.fillStyle = '#070a0d'
    ctx.fillRect(0, 0, W, H)
    const t = tick

    drawLabel(ctx, "Attacker's tree", 90, 14, '#c8a951', 9)
    drawBox(ctx, 50, 22, 76, 22, '#1a1010', '#8a1a1a', 4)
    drawLabel(ctx, 'fake root', 88, 37, '#ffb3b3', 9)
    ctx.strokeStyle = '#26343a'; ctx.lineWidth = 1
    ctx.beginPath(); ctx.moveTo(72, 44); ctx.lineTo(52, 72); ctx.stroke()
    ctx.beginPath(); ctx.moveTo(106, 44); ctx.lineTo(126, 72); ctx.stroke()
    drawBox(ctx, 26, 72, 52, 20, '#1a1010', '#8a1a1a', 4)
    drawLabel(ctx, 'f-leaf1', 52, 86, '#ffb3b3', 9)
    drawBox(ctx, 100, 72, 52, 20, '#1a1010', '#8a1a1a', 4)
    drawLabel(ctx, 'f-leaf2', 126, 86, '#ffb3b3', 9)

    drawLabel(ctx, 'Public bulletin board', 358, 14, '#8aa1a8', 9)
    drawBox(ctx, 293, 22, 130, 22, '#1a2a1a', '#2a6a3a', 4)
    drawLabel(ctx, 'PUBLIC ROOT', 358, 37, '#8fc8b0', 9)
    ctx.strokeStyle = '#26343a'; ctx.lineWidth = 1
    ctx.beginPath(); ctx.moveTo(338, 44); ctx.lineTo(318, 72); ctx.stroke()
    ctx.beginPath(); ctx.moveTo(378, 44); ctx.lineTo(398, 72); ctx.stroke()
    drawBox(ctx, 293, 72, 50, 20, '#1a2a1a', '#2a6a3a', 4)
    drawLabel(ctx, 'leaf1', 318, 86, '#8fc8b0', 9)
    drawBox(ctx, 363, 72, 50, 20, '#1a2a1a', '#2a6a3a', 4)
    drawLabel(ctx, 'leaf2', 388, 86, '#8fc8b0', 9)

    if (t > 10) {
      arrowH(ctx, 168, 33, 208, '#c8a951')
      arrowH(ctx, 290, 33, 250, '#c8a951')
      drawBox(ctx, 208, 22, 40, 22, '#1a150a', '#c8a951', 4)
      drawLabel(ctx, '≠', 228, 38, '#c8a951', 14)
    }
    if (t > 25) {
      drawBox(ctx, 10, 110, 460, 28, '#0c1114', '#26343a', 4)
      drawLabel(ctx, '[AUDIT] Fake root ≠ Bulletin Board root — receipt INVALID', 235, 128, '#c8a951', 9)
    }
    if (t > 42) {
      drawBox(ctx, 10, 146, 460, 24, '#0c1114', '#26343a', 4)
      drawLabel(ctx, '[WITNESS] Root cross-check: Independent Witness 1 — MATCH FAILED', 235, 162, '#e24b4a', 9)
    }

    tick++
    if (tick > 72) tick = 0
  }, 80)
  return () => clearInterval(id)
}

function animPanicPin(ctx) {
  let tick = 0
  const id = setInterval(() => {
    const W = ctx.canvas.width, H = ctx.canvas.height
    ctx.clearRect(0, 0, W, H)
    ctx.fillStyle = '#070a0d'
    ctx.fillRect(0, 0, W, H)
    const t = tick

    drawBox(ctx, 20, 10, 200, 100, '#1a2a1a', '#2a6a3a', 8)
    drawLabel(ctx, 'FRONTEND (coercer sees)', 120, 26, '#8aa1a8', 9)
    drawLabel(ctx, '✓ Vote Recorded!', 120, 54, '#8fc8b0', 13)
    drawLabel(ctx, 'Receipt: 0xf3a9...', 120, 74, '#8fc8b0', 10)
    drawLabel(ctx, 'Thank you for voting.', 120, 92, '#8aa1a8', 9)

    if (t > 12) {
      drawBox(ctx, 240, 115, 220, 28, '#1a1a1a', '#26343a', 4)
      drawLabel(ctx, 'INSERT INTO votes', 350, 133, '#8aa1a8', 10)
      drawLabel(ctx, 'is_decoy = 1  ← server side', 350, 152, t > 25 ? '#e24b4a' : '#8aa1a8', t > 25 ? 10 : 9)
    }
    if (t > 36) {
      drawBox(ctx, 20, 120, 460, 15, '#10161a', '#26343a', 3)
      const barW = Math.min(460, (t - 36) * 14)
      drawBox(ctx, 20, 120, barW, 15, '#1a2a3a', '#5a8fa8', 3)
      drawLabel(ctx, 'Tally reveal scanning...', 250, 133, '#5a8fa8', 9)
    }
    if (t > 62) {
      drawBox(ctx, 20, 140, 460, 24, '#1a0a0a', '#8a1a1a', 4)
      drawLabel(ctx, '[SKIP] Coercion Tag → is_decoy=1 → Row excluded from tally', 240, 156, '#c8a951', 9)
    }

    tick++
    if (tick > 85) tick = 0
  }, 80)
  return () => clearInterval(id)
}

function animDomHijack(ctx) {
  let tick = 0
  const id = setInterval(() => {
    const W = ctx.canvas.width, H = ctx.canvas.height
    ctx.clearRect(0, 0, W, H)
    ctx.fillStyle = '#070a0d'
    ctx.fillRect(0, 0, W, H)
    const t = tick

    const bannerX = Math.max(0, 480 - t * 18)
    if (bannerX < 480) {
      drawBox(ctx, bannerX, 4, 460, 22, '#1a0505', '#8a1a1a', 4)
      drawLabel(ctx, '⚠ MALICIOUS EXTENSION — content_script.js injected', 240 + bannerX / 2, 19, '#ffb3b3', 9)
    }

    const swapped = t > 22
    const glitch = t > 20 && t < 28 && tick % 4 < 2
    drawBox(ctx, 30, 50, 150, 60, swapped ? '#1a1a1a' : '#1a2a3a', swapped ? '#26343a' : '#5a8fa8', 8)
    drawLabel(ctx, glitch ? 'Candidate B' : 'Candidate A', 105, 85, swapped ? '#26343a' : '#8fc8b0', 14)
    if (swapped) drawLabel(ctx, '(deselected by malware)', 105, 102, '#26343a', 9)

    if (t > 18) {
      ctx.strokeStyle = '#e24b4a'; ctx.lineWidth = 1.5
      ctx.setLineDash([3, 3])
      ctx.beginPath(); ctx.moveTo(184, 80); ctx.lineTo(246, 80); ctx.stroke()
      ctx.setLineDash([])
      drawLabel(ctx, 'SWAP', 215, 75, '#e24b4a', 9)
    }

    if (t > 20) {
      drawBox(ctx, 250, 50, 150, 60, '#2a1a1a', '#e24b4a', 8)
      drawLabel(ctx, 'Candidate B', 325, 85, '#ffb3b3', 14)
      drawLabel(ctx, '← injected by malware', 325, 102, '#e24b4a', 9)
    }

    if (t > 30) {
      drawBox(ctx, 20, 125, 440, 24, '#0c1114', '#26343a', 4)
      drawLabel(ctx, '[MALWARE] DOM mutation on #candidate-id — plaintext altered before AES-GCM', 230, 141, '#e24b4a', 9)
    }
    if (t > 46) {
      drawBox(ctx, 20, 155, 440, 20, '#10161a', '#26343a', 4)
      drawLabel(ctx, 'Future fix: kiosk + CSP hardening + out-of-band confirmation', 230, 168, '#5a8fa8', 9)
    }

    tick++
    if (tick > 72) tick = 0
  }, 80)
  return () => clearInterval(id)
}

function animDbTamper(ctx) {
  let tick = 0
  const id = setInterval(() => {
    const W = ctx.canvas.width, H = ctx.canvas.height
    ctx.clearRect(0, 0, W, H)
    ctx.fillStyle = '#070a0d'
    ctx.fillRect(0, 0, W, H)
    const t = tick
    const tampered = t > 20

    const rootColor = tampered ? '#e24b4a' : '#8fc8b0'
    drawBox(ctx, 185, 10, 110, 24, tampered ? '#1a0505' : '#1a2a1a', rootColor, 6)
    drawLabel(ctx, 'MERKLE ROOT', 240, 26, rootColor, 9)

    ctx.strokeStyle = tampered && t > 25 ? '#e24b4a' : '#26343a'
    ctx.lineWidth = tampered && t > 25 ? 2 : 1
    if (tampered && t > 25) ctx.setLineDash([4, 4])
    ctx.beginPath(); ctx.moveTo(220, 34); ctx.lineTo(120, 70); ctx.stroke()
    ctx.beginPath(); ctx.moveTo(260, 34); ctx.lineTo(360, 70); ctx.stroke()
    ctx.setLineDash([])

    drawBox(ctx, 70, 70, 100, 24, '#1a2a1a', '#2a6a3a', 4)
    drawLabel(ctx, 'leaf #1  OK', 120, 86, '#8fc8b0', 9)

    const lc = tampered ? '#e24b4a' : '#2a6a3a'
    drawBox(ctx, 310, 70, 100, 24, tampered ? '#1a0505' : '#1a2a1a', lc, 4)
    drawLabel(ctx, tampered ? 'leaf #4  ✗ TAMPER' : 'leaf #4  OK', 360, 86, tampered ? '#ffb3b3' : '#8fc8b0', 9)

    if (t > 30) {
      drawBox(ctx, 160, 110, 160, 24, tampered ? '#8a1a1a' : '#1a2a1a', tampered ? '#e24b4a' : '#8fc8b0', 4)
      drawLabel(ctx, tampered ? '⚠ TAMPER DETECTED' : '✓ OK', 240, 126, tampered ? '#ffb3b3' : '#8fc8b0', 11)
    }
    if (t > 36) {
      drawBox(ctx, 20, 142, 440, 24, '#0c1114', '#26343a', 4)
      drawLabel(ctx, '[CRITICAL] Leaf #4 hash mismatch — DB compromised', 230, 158, '#e24b4a', 9)
    }

    tick++
    if (tick > 65) tick = 0
  }, 80)
  return () => clearInterval(id)
}

const ANIM_MAP = {
  credential: animCredential,
  double_vote: animDoubleVote,
  fake_shard: animFakeShard,
  merkle_forgery: animMerkle,
  panic_pin: animPanicPin,
  dom_hijack: animDomHijack,
  db_tamper: animDbTamper,
}

// ─── HELPER ───────────────────────────────────────────────────────────────────
function nowStr() { return new Date().toLocaleTimeString() }

// ─── COMPONENTS ───────────────────────────────────────────────────────────────

function AttackButton({ attack, selected, onSelect }) {
  const isSelected = selected === attack.id
  return (
    <button
      onClick={() => onSelect(attack.id)}
      style={{
        width: '100%',
        textAlign: 'left',
        border: `1px solid ${isSelected ? SEV_COLOR[attack.severity] : '#26343a'}`,
        borderLeft: `4px solid ${SEV_COLOR[attack.severity]}`,
        borderRadius: 6,
        background: isSelected ? '#1b1717' : '#10161a',
        color: '#d7e2dc',
        padding: 11,
        marginBottom: 7,
        cursor: 'pointer',
        fontFamily: 'monospace',
      }}
    >
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6 }}>
        <span style={{ color: SEV_COLOR[attack.severity], fontSize: 10 }}>{attack.severity.toUpperCase()}</span>
        <span style={{ color: STATUS_COLOR[attack.status] || '#8aa1a8', fontSize: 10 }}>{attack.status.toUpperCase()}</span>
      </div>
      <div style={{ fontWeight: 700, fontSize: 12 }}>{attack.title}</div>
      <div style={{ color: '#8aa1a8', fontSize: 10, marginTop: 3 }}>{attack.target}</div>
    </button>
  )
}

function Panel({ title, children, style }) {
  return (
    <div style={{ border: '1px solid #26343a', borderRadius: 6, background: '#0c1114', overflow: 'hidden', marginBottom: 14, ...style }}>
      <div style={{ background: '#10161a', borderBottom: '1px solid #26343a', padding: '9px 13px', color: '#8aa1a8', fontSize: 10, letterSpacing: 2 }}>
        {title}
      </div>
      {children}
    </div>
  )
}

function TerminalView({ lines }) {
  return (
    <div style={{ padding: 14, minHeight: 160 }}>
      {lines.slice(-14).map((line, i) => (
        <div key={i} style={{
          color: line.startsWith('!') ? '#ff6b6b' : line.startsWith('>') ? '#c8a951' : '#8fc8b0',
          fontSize: 11, lineHeight: 1.7, fontFamily: 'monospace',
        }}>
          {line}
        </div>
      ))}
    </div>
  )
}

function AuditLog({ entries }) {
  return (
    <div style={{ padding: 12, minHeight: 200 }}>
      {entries.map((a, i) => (
        <div key={i} style={{ display: 'grid', gridTemplateColumns: '70px 44px 1fr', gap: 6, padding: '6px 0', borderBottom: '1px solid #1b252a', fontSize: 10 }}>
          <span style={{ color: '#5a8fa8' }}>{a.time}</span>
          <span style={{
            color: a.level === 'PASS' ? '#8fc8b0'
              : a.level === 'RISK' || a.level === 'WARN' ? '#c8a951'
              : a.level === 'ERR' ? '#ff6b6b'
              : '#8aa1a8',
          }}>{a.level}</span>
          <span style={{ color: '#8aa1a8' }}>{a.text}</span>
        </div>
      ))}
    </div>
  )
}

function DbView({ dbState }) {
  const rows = [
    { id: 'latest', nullifier: dbState.nullifier, aes_key: 'wrapped:x25519', is_decoy: dbState.is_decoy, merkle_leaf: dbState.leaf, timestamp: dbState.status },
    { id: 'board', nullifier: 'private', aes_key: 'private', is_decoy: 'hidden', merkle_leaf: dbState.votes + ' votes', timestamp: 'live' },
  ]
  const colW = '50px 110px 90px 70px 100px 80px'
  return (
    <div style={{ padding: '8px 12px 12px', overflowX: 'auto' }}>
      <div style={{ display: 'grid', gridTemplateColumns: colW, gap: 6, color: '#c8a951', fontSize: 9, marginBottom: 6 }}>
        {DB_COLS.map(c => <div key={c}>{c}</div>)}
      </div>
      {rows.map((row, i) => (
        <div key={i} style={{ display: 'grid', gridTemplateColumns: colW, gap: 6, color: '#8aa1a8', fontSize: 9, padding: '5px 0', borderTop: '1px solid #1b252a' }}>
          {DB_COLS.map(c => <div key={c} style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{row[c]}</div>)}
        </div>
      ))}
    </div>
  )
}

function TabPanel({ attack, result, activeTab, onTabChange }) {
  const tabs = ['flow', 'defense', 'failure', 'future']
  const content = {
    flow: [['Attack surface', attack.short], ['Payload', attack.payload.join(' | ')], ['Operator commands', attack.commands.join(' → ')]],
    defense: [['Current defense', attack.defense], ['Runtime result', result ? result.summary : 'Run the simulation to collect telemetry.']],
    failure: [['Known limitation', attack.limitation], ['Honest note', attack.status === 'defended' ? 'This attack is currently blocked in the demo pipeline.' : 'This remains a design risk or partial exposure.']],
    future: [['Future work', attack.future], ['Architecture direction', 'Move trust anchors outside the single server: transparency logs, mix nets, independent root witnesses, and hardware-derived secrets.']],
  }[activeTab]

  return (
    <div style={{ border: '1px solid #26343a', borderRadius: 6, background: '#0c1114', overflow: 'hidden', marginTop: 14 }}>
      <div style={{ display: 'flex', background: '#10161a', borderBottom: '1px solid #26343a' }}>
        {tabs.map(tab => (
          <button key={tab} onClick={() => onTabChange(tab)} style={{
            padding: '10px 16px', background: activeTab === tab ? '#172126' : 'transparent',
            color: activeTab === tab ? '#d7e2dc' : '#8aa1a8',
            border: 'none', borderBottom: `2px solid ${activeTab === tab ? '#8a1a1a' : 'transparent'}`,
            cursor: 'pointer', fontFamily: 'monospace', letterSpacing: 1, fontSize: 11,
          }}>
            {tab.toUpperCase()}
          </button>
        ))}
      </div>
      <div style={{ padding: 14, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
        {content.map(([label, text]) => (
          <div key={label} style={{ border: '1px solid #26343a', borderRadius: 6, padding: 14, background: '#070a0d' }}>
            <div style={{ color: '#c8a951', fontSize: 10, letterSpacing: 2, marginBottom: 7 }}>{label.toUpperCase()}</div>
            <div style={{ color: '#8aa1a8', fontSize: 12, lineHeight: 1.65 }}>{text}</div>
          </div>
        ))}
        {result?.events?.map((event, i) => (
          <div key={i} style={{ border: '1px solid #26343a', borderRadius: 6, padding: 14, background: '#070a0d' }}>
            <div style={{ marginBottom: 6 }}>
              <span style={{ background: (STATUS_COLOR[event.status] || '#c8a951') + '22', color: STATUS_COLOR[event.status] || '#c8a951', fontSize: 10, padding: '3px 8px', borderRadius: 4, letterSpacing: 1 }}>
                {event.status.toUpperCase()}
              </span>
            </div>
            <div style={{ fontWeight: 700, fontSize: 12, marginBottom: 4, color: '#d7e2dc' }}>{event.title}</div>
            <div style={{ color: '#8aa1a8', fontSize: 12, lineHeight: 1.65 }}>{event.detail}</div>
          </div>
        ))}
      </div>
    </div>
  )
}

// ─── MAIN COMPONENT ───────────────────────────────────────────────────────────

export default function AttackLab() {
  const [selected, setSelected] = useState(ATTACKS[0].id)
  const [rollNo, setRollNo] = useState('')
  const [pin, setPin] = useState('')
  const [allowLiveProbe, setAllowLiveProbe] = useState(false)
  const [terminal, setTerminal] = useState([
    '$ boot attacker console',
    '$ load secure-vote profile',
    '$ awaiting scenario...',
  ])
  const [audit, setAudit] = useState([
    { time: nowStr(), level: 'INFO', text: 'Attack Lab initialized in educational mode.' },
    { time: nowStr(), level: 'INFO', text: 'No production exploit code will be executed.' },
  ])
  const [dbState, setDbState] = useState({ nullifier: 'b3f4d10a...', is_decoy: '0', status: 'live', leaf: 'a3f9...', votes: 3 })
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [activeTab, setActiveTab] = useState('flow')

  const canvasRef = useRef(null)
  const animCleanupRef = useRef(null)

  const attack = useMemo(() => ATTACKS.find(a => a.id === selected), [selected])

  const stopAnim = useCallback(() => {
    if (animCleanupRef.current) { animCleanupRef.current(); animCleanupRef.current = null }
  }, [])

  const startAnim = useCallback(() => {
    stopAnim()
    const canvas = canvasRef.current
    if (!canvas) return
    const ctx = canvas.getContext('2d')
    const fn = ANIM_MAP[attack.animType]
    if (fn) animCleanupRef.current = fn(ctx)
  }, [attack, stopAnim])

  // Reset on attack change
  useEffect(() => {
    setResult(null); setError(''); setActiveTab('flow')
    stopAnim()
    const canvas = canvasRef.current
    if (canvas) { const ctx = canvas.getContext('2d'); ctx.clearRect(0, 0, canvas.width, canvas.height) }
  }, [selected, stopAnim])

  useEffect(() => () => stopAnim(), [stopAnim])

  function addAudit(level, text) {
    setAudit(prev => [{ time: nowStr(), level, text }, ...prev].slice(0, 12))
  }
  function addTerminal(line) {
    setTerminal(prev => [...prev, line])
  }

  async function runAttack() {
    setLoading(true); setError(''); setResult(null)
    const lines = attack.commands.map(c => `$ ${c}`)
    setTerminal([...lines, '$ stream defense telemetry'])
    addAudit('WARN', `${attack.title} simulation started.`)
    startAnim()

    try {
      let data
      if (attack.backend) {
        const resp = await fetch(`${API_BASE}/attack/run`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            scenario_id: attack.backend,
            roll_no: rollNo || null,
            pin: pin || null,
            allow_live_probe: allowLiveProbe,
          }),
        })
        if (!resp.ok) { const e = await resp.json(); throw new Error(e.detail || resp.statusText) }
        data = await resp.json()
      } else {
        // Frontend-only simulation (dom_hijack, db_tamper have no backend route)
        data = {
          verdict: attack.status === 'defended' ? 'defended' : attack.status,
          summary: attack.defense,
          events: [
            { status: 'attack', title: 'Payload staged', detail: attack.short },
            { status: attack.status === 'defended' ? 'blocked' : 'observed', title: 'System response', detail: attack.defense },
            { status: attack.status === 'defended' ? 'defended' : 'failed', title: 'Residual risk', detail: attack.limitation },
          ],
        }
      }

      setResult(data)

      // DB side-effects
      if (attack.id === 'double_vote') setDbState(s => ({ ...s, nullifier: 'COLLISION BLOCKED', status: 'constraint' }))
      if (attack.id === 'panic_pin') setDbState(s => ({ ...s, is_decoy: '1 (decoy)', status: 'skipped' }))
      if (attack.id === 'db_tamper') setDbState(s => ({ ...s, leaf: 'HASH MISMATCH', status: 'TAMPER' }))

      addTerminal(`> verdict=${data.verdict}`)
      addTerminal(`> summary="${data.summary.slice(0, 60)}..."`)
      addTerminal('> simulation complete')
      addAudit(data.verdict === 'defended' ? 'PASS' : 'RISK', data.summary.slice(0, 60))
    } catch (err) {
      const msg = err.message || 'Unknown error'
      setError(msg)
      addTerminal(`! ${msg}`)
      addAudit('ERR', msg)
    }
    setLoading(false)
  }

  return (
    <div style={{ minHeight: '100vh', background: '#070a0d', color: '#d7e2dc', padding: 20, fontFamily: 'monospace' }}>
      {/* Title bar */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 16, border: '1px solid #26343a', padding: '10px 14px', borderRadius: 6, background: '#10161a' }}>
        <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#e24b4a', display: 'inline-block' }} />
        <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#ef9f27', display: 'inline-block' }} />
        <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#639922', display: 'inline-block' }} />
        <span style={{ flex: 1, textAlign: 'center', color: '#8aa1a8', fontSize: 11 }}>secure-vote — attacker dashboard</span>
        <span style={{ color: '#ffb3b3', border: '1px solid #8a1a1a', padding: '3px 8px', borderRadius: 4, fontSize: 10 }}>EDUCATIONAL SANDBOX</span>
      </div>

      {/* 3-col grid */}
      <div style={{ display: 'grid', gridTemplateColumns: '250px 1.1fr 0.9fr', gap: 14, alignItems: 'start' }}>
        {/* LEFT: Attack list */}
        <div>
          <div style={{ color: '#8aa1a8', fontSize: 10, letterSpacing: 2, marginBottom: 10 }}>ATTACK VECTORS</div>
          {ATTACKS.map(a => (
            <AttackButton key={a.id} attack={a} selected={selected} onSelect={id => { setSelected(id) }} />
          ))}
        </div>

        {/* MIDDLE */}
        <div>
          <Panel title="LIVE TERMINAL">
            <div style={{ padding: 14 }}>
              <div style={{ color: '#ffb3b3', fontSize: 11, marginBottom: 4 }}>target: {attack.target}</div>
              <div style={{ fontSize: 20, fontWeight: 700, fontFamily: 'Georgia, serif', marginBottom: 6 }}>{attack.title}</div>
              <div style={{ color: '#8aa1a8', fontSize: 12, lineHeight: 1.5, marginBottom: 12 }}>{attack.short}</div>

              {attack.hasInputs && (
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginBottom: 10 }}>
                  <input value={rollNo} onChange={e => setRollNo(e.target.value)} placeholder="roll number" autoComplete="off"
                    style={{ background: '#070a0d', color: '#d7e2dc', border: '1px solid #26343a', borderRadius: 4, padding: 8, fontFamily: 'monospace', fontSize: 11 }} />
                  <input value={pin} onChange={e => setPin(e.target.value.replace(/\D/g, '').slice(0, 12))} placeholder="leaked PIN" type="password" inputMode="numeric" autoComplete="off"
                    style={{ background: '#070a0d', color: '#d7e2dc', border: '1px solid #26343a', borderRadius: 4, padding: 8, fontFamily: 'monospace', fontSize: 11 }} />
                </div>
              )}

              {attack.id === 'double_vote' && (
                <label style={{ display: 'flex', alignItems: 'center', gap: 8, color: '#8aa1a8', fontSize: 11, marginBottom: 10 }}>
                  <input type="checkbox" checked={allowLiveProbe} onChange={e => setAllowLiveProbe(e.target.checked)} />
                  allow live duplicate insert probe
                </label>
              )}

              {/* Animation canvas */}
              <div style={{ position: 'relative', width: '100%', height: 180, marginBottom: 12, borderRadius: 4, overflow: 'hidden', background: '#070a0d', border: '1px solid #1b252a' }}>
                <canvas ref={canvasRef} width={480} height={180} style={{ width: '100%', height: '100%' }} />
                {!loading && !result && (
                  <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#26343a', fontSize: 11, pointerEvents: 'none' }}>
                    → run simulation to start animation
                  </div>
                )}
              </div>

              <button
                onClick={runAttack}
                disabled={loading}
                style={{ width: '100%', border: 'none', borderRadius: 6, background: loading ? '#4a1010' : '#8a1a1a', color: 'white', padding: 13, letterSpacing: 2, fontFamily: 'monospace', fontSize: 12, cursor: loading ? 'default' : 'pointer', transition: 'background .2s' }}
              >
                {loading ? 'RUNNING ATTACK...' : 'EXECUTE SIMULATION'}
              </button>
              {error && <div style={{ color: '#ff6b6b', marginTop: 10, fontSize: 11 }}>{error}</div>}
            </div>
          </Panel>

          <Panel title="DUMMY SHELL">
            <TerminalView lines={terminal} />
          </Panel>
        </div>

        {/* RIGHT */}
        <div>
          <Panel title="DUMMY LIVE DATABASE">
            <DbView dbState={dbState} />
          </Panel>
          <Panel title="DUMMY AUDIT LOG">
            <AuditLog entries={audit} />
          </Panel>
        </div>
      </div>

      {/* Bottom tab panel */}
      <TabPanel attack={attack} result={result} activeTab={activeTab} onTabChange={setActiveTab} />
    </div>
  )
}