import { useEffect, useMemo, useState } from 'react'
import api from '../api'

const ATTACKS = [
  {
    id: 'credential_stuffing',
    backend: 'credential_stuffing',
    title: 'Credential stuffing',
    severity: 'high',
    status: 'defended',
    target: 'WebAuthn gate',
    short: 'Leaked roll number and PIN are tried against the vote endpoint.',
    payload: ['roll_no=101', 'pin=1234', 'assertion=null'],
    commands: [
      'load leaked_credentials.csv',
      'try roll_no + pin against /vote/complete',
      'observe WebAuthn challenge failure'
    ],
    defense: 'Touch ID/WebAuthn requires the enrolled Secure Enclave private key. PIN knowledge alone cannot sign the server challenge.',
    limitation: 'A stolen PIN can still harm privacy if PIN-derived secrets are weak. Use high-entropy authenticator-derived secrets for a production system.',
    future: 'Use WebAuthn PRF or platform-keystore secrets so the voting secret is generated by hardware, not memorized by the voter.'
  },
  {
    id: 'double_vote',
    backend: 'double_vote',
    title: 'Double vote',
    severity: 'high',
    status: 'defended',
    target: 'votes.nullifier',
    short: 'The same voter attempts to submit a second ballot.',
    payload: ['duplicate nullifier', 'same election id', 'new ciphertext'],
    commands: [
      'select latest nullifier from votes',
      'attempt duplicate insert',
      'expect UNIQUE constraint rejection'
    ],
    defense: 'The nullifier is stable per voter per election, and the votes table enforces UNIQUE(nullifier).',
    limitation: 'Old demo voters created before the stable-nullifier migration should be re-registered for a clean demo.',
    future: 'Add formal election IDs and signed election manifests so nullifier domains cannot be accidentally reused.'
  },
  {
    id: 'fake_shard',
    backend: 'fake_shard',
    title: 'Fake trustee shard',
    severity: 'critical',
    status: 'defended',
    target: 'admin reveal',
    short: 'A malicious trustee submits a corrupted Shamir shard.',
    payload: ['trustee_id=mallory', 'shard=1-deadbeef'],
    commands: [
      'submit forged shard',
      'verify against Feldman commitments',
      'reject before shard store'
    ],
    defense: 'Feldman VSS commitments reject shards that do not match the key-generation polynomial.',
    limitation: 'Commitments must be public and independently archived. If only the database stores them, a DB admin is still a trust anchor.',
    future: 'Publish VSS commitments to an append-only transparency log or blockchain before voting begins.'
  },
  {
    id: 'merkle_forgery',
    backend: 'merkle_forgery',
    title: 'Merkle root spoof',
    severity: 'medium',
    status: 'defended',
    target: 'receipt verifier',
    short: 'An attacker invents a fake receipt path and fake root.',
    payload: ['fake leaf', 'fake proof path', 'fake root'],
    commands: [
      'generate fake leaf',
      'build attacker-controlled root',
      'compare against /election/root'
    ],
    defense: 'Receipts verify against the public bulletin-board root, not a root supplied by the attacker.',
    limitation: 'If the voter checks only inside a compromised browser, an extension could spoof both receipt and root response.',
    future: 'Mirror roots to independent auditors, signed SMS, newspaper hash, blockchain, or CT-style transparency logs.'
  },
  {
    id: 'panic_pin',
    backend: 'panic_pin',
    title: 'Panic PIN coercion',
    severity: 'medium',
    status: 'defended',
    target: 'duress flow',
    short: 'A coercer watches the voter cast a ballot using a panic PIN.',
    payload: ['pin=panic', 'is_decoy=1', 'normal receipt'],
    commands: [
      'cast with panic PIN',
      'return normal success UI',
      'skip decoy row during reveal'
    ],
    defense: 'The surface flow stays normal, but final tally skips rows marked is_decoy=1.',
    limitation: 'Coercion resistance can leak through timing, payload size, or UI differences if the panic path diverges.',
    future: 'Use constant-size payloads, timing padding, and a revoting model where the last valid vote wins.'
  },
  {
    id: 'dom_hijack',
    title: 'DOM ballot swap',
    severity: 'critical',
    status: 'partially exposed',
    target: 'browser state',
    short: 'A malicious browser extension changes the selected candidate before encryption.',
    payload: ['content script', 'React state mutation', 'candidate swap'],
    commands: [
      'hook candidate click handler',
      'replace selected candidate before AES-GCM',
      'let user sign altered ciphertext'
    ],
    defense: 'Ciphertext tampering after encryption fails. WebAuthn binds the signed challenge to the enrolled device.',
    limitation: 'If malware changes the plaintext before encryption, the backend cannot know the user intended a different candidate.',
    future: 'Use locked-down kiosk mode, extension-free browser profiles, CSP hardening, and out-of-band candidate confirmation.'
  },
  {
    id: 'pin_keylogger',
    title: 'PIN keylogger',
    severity: 'critical',
    status: 'partially exposed',
    target: 'PIN input',
    short: 'A malicious extension records the voting PIN as the voter types.',
    payload: ['keydown listener', 'PIN exfiltration', 'privacy attack'],
    commands: [
      'attach keydown listener',
      'capture numeric PIN',
      'attempt vote from remote device'
    ],
    defense: 'The attacker still cannot vote without the WebAuthn private key.',
    limitation: 'A low-entropy PIN can weaken anonymity and receipt secrecy if stolen.',
    future: 'Move voter secrets into WebAuthn PRF or a platform keystore; make the PIN only unlock local hardware.'
  },
  {
    id: 'timing_correlation',
    title: 'Timing correlation',
    severity: 'medium',
    status: 'future work',
    target: 'network metadata',
    short: 'An observer correlates login/vote timing with leaf insertion order.',
    payload: ['IP timestamp', 'vote_count delta', 'leaf index'],
    commands: [
      'watch /vote/complete timing',
      'poll /election/root vote_count',
      'correlate voter session to leaf index'
    ],
    defense: 'Cryptography protects ballot contents, nullifiers, and tamper evidence.',
    limitation: 'Traffic metadata can still leak who voted when, especially in small elections.',
    future: 'Use mix nets, batching, delayed publication, cover traffic, and anonymity networks for stronger metadata privacy.'
  },
  {
    id: 'db_tamper',
    title: 'Database tamper',
    severity: 'high',
    status: 'defended',
    target: 'votes table',
    short: 'A database admin edits ciphertext or Merkle leaves after voting.',
    payload: ['UPDATE votes', 'modified ciphertext', 'root mismatch'],
    commands: [
      'mutate encrypted_vote bytes',
      'recompute detection chain',
      'observe Merkle mismatch'
    ],
    defense: 'Merkle roots anchor the ledger. Receipt verification fails if DB rows change without a matching public root.',
    limitation: 'A single-server public board can be rewritten by a fully compromised server unless roots are externally archived.',
    future: 'Publish roots to independent witnesses, blockchain, or a signed append-only transparency log.'
  }
]

const SEVERITY_COLOR = {
  critical: '#8a1a1a',
  high: '#a45b12',
  medium: '#2a6a3a'
}

const VERDICT_COLOR = {
  defended: '#8fc8b0',
  'partially exposed': '#c8a951',
  'future work': '#5a8fa8',
  vulnerable: '#ff6b6b',
  needs_data: '#8899aa'
}

const DB_COLUMNS = ['id', 'nullifier', 'aes_key', 'is_decoy', 'merkle_leaf', 'timestamp']

function shortHash(value) {
  if (!value) return 'pending'
  return `${value.slice(0, 10)}...${value.slice(-6)}`
}

function now() {
  return new Date().toLocaleTimeString()
}

const THEATER_CSS = `
@keyframes pulseGreen { 0%,100% { box-shadow: 0 0 0 #8fc8b0; } 50% { box-shadow: 0 0 22px #8fc8b0; } }
@keyframes pulseRed { 0%,100% { box-shadow: 0 0 0 #ff6b6b; } 50% { box-shadow: 0 0 24px #ff6b6b; } }
@keyframes slideRow { 0% { transform: translateX(-140px); opacity: .2; } 65% { transform: translateX(0); opacity: 1; } 100% { transform: translateX(18px) scale(.75); opacity: 0; } }
@keyframes glowNullifier { 0%,100% { color: #8aa1a8; } 50% { color: #ff6b6b; text-shadow: 0 0 14px #ff6b6b; } }
@keyframes radar { 0% { left: 0; opacity: .3; } 50% { opacity: 1; } 100% { left: 92%; opacity: .3; } }
@keyframes arrowCompare { 0% { transform: translateX(-70px); opacity: .2; } 60% { transform: translateX(0); opacity: 1; } 100% { transform: translateX(0); opacity: 1; } }
@keyframes maskDecoy { 0%,50% { color: #ff6b6b; } 100% { color: #8aa1a8; filter: blur(3px); } }
@keyframes scanVotes { 0% { width: 0; } 100% { width: 100%; } }
@keyframes glitch { 0%,100% { transform: translate(0); } 20% { transform: translate(-3px, 1px); color: #ff6b6b; } 40% { transform: translate(2px, -1px); color: #8fc8b0; } 60% { transform: translate(-1px, 2px); } }
@keyframes bannerDrop { 0% { transform: translateY(-44px); opacity: 0; } 100% { transform: translateY(0); opacity: 1; } }
@keyframes snapLine { 0%,45% { background: #8fc8b0; transform: rotate(0); } 100% { background: #ff6b6b; transform: rotate(8deg); } }
@keyframes tamperPulse { 0%,100% { background: #172126; color: #8fc8b0; } 50% { background: #8a1a1a; color: white; } }
.atk-chip { border: 1px solid #26343a; border-radius: 6px; padding: 12px; background: #070a0d; }
.pin-ok { animation: pulseGreen 1.2s ease-in-out 2; border-color: #8fc8b0 !important; }
.bio-fail { animation: pulseRed 1.2s ease-in-out 2; border-color: #ff6b6b !important; }
.incoming-row { animation: slideRow 2.2s ease forwards; }
.nullifier-hot { animation: glowNullifier 1.1s ease-in-out 2; }
.radar-beam { animation: radar 2s ease-in-out forwards; }
.compare-arrow { animation: arrowCompare 1.5s ease-out forwards; }
.decoy-mask { animation: maskDecoy 2.6s ease forwards; }
.scan-bar { animation: scanVotes 2.2s ease-out forwards; }
.glitch-text { animation: glitch .65s ease-in-out 3; }
.malware-banner { animation: bannerDrop .7s ease-out forwards; }
.snap-line { animation: snapLine 1.4s ease forwards; }
.tamper-badge { animation: tamperPulse 1s ease-in-out infinite; }
`

function attackExtraLines(id) {
  const lines = {
    credential_stuffing: ['[PIN] hash match: TRUE', '[ERROR] 401: WebAuthn Assertion Missing. Hardware Signature Required.'],
    double_vote: ['SQLITE_CONSTRAINT: UNIQUE constraint failed: votes.nullifier'],
    fake_shard: ['[VSS] g^y != product(C_i ^ x^i)', '[VSS] Shard checksum mismatch. Entry into Shard Store: REJECTED.'],
    merkle_forgery: ['[AUDIT] Root cross-check with Independent Witness 1 ... MATCH FAILED.'],
    panic_pin: ['[DECOY] Coercion tag stored.', '[REVEAL] Coercion Tag: Skipping Row.'],
    dom_hijack: ['[MALWARE DETECTED] DOM Mutation observed on element #candidate-id.'],
    db_tamper: ['[DETECTION] Integrity check running...', '[CRITICAL] Leaf hash does not match sequential history. Database compromised.']
  }
  return lines[id] || []
}

function attackAuditLine(id) {
  const lines = {
    credential_stuffing: '[ERROR] 401: WebAuthn Assertion Missing. Hardware Signature Required.',
    double_vote: 'SQLITE_CONSTRAINT: UNIQUE constraint failed: votes.nullifier.',
    fake_shard: '[VSS] Shard checksum mismatch. Entry into Shard Store: REJECTED.',
    merkle_forgery: '[AUDIT] Root cross-check with Independent Witness 1 ... MATCH FAILED.',
    panic_pin: '[REVEAL] Coercion Tag: Skipping Row.',
    dom_hijack: '[MALWARE DETECTED] DOM Mutation observed on element #candidate-id.',
    db_tamper: '[CRITICAL] Leaf hash does not match sequential history. Database compromised.'
  }
  return lines[id]
}

function Theater({ attackId, board }) {
  if (attackId === 'credential_stuffing') {
    return (
      <div className="atk-chip" style={{ display: 'grid', gridTemplateColumns: '1fr 70px 1fr', gap: 12, alignItems: 'center', marginBottom: 14 }}>
        <div className="atk-chip pin-ok">
          <div style={{ color: '#8fc8b0', fontSize: 11 }}>GATE 1</div>
          <div style={{ color: 'white', fontWeight: 700 }}>PIN CHECK PASSED</div>
        </div>
        <div style={{ textAlign: 'center', color: '#c8a951' }}>--&gt;</div>
        <div className="atk-chip bio-fail">
          <div style={{ color: '#ff6b6b', fontSize: 11 }}>GATE 2</div>
          <div style={{ color: 'white', fontWeight: 700 }}>HARDWARE WALL</div>
          <div style={{ color: '#8aa1a8', fontSize: 11, marginTop: 4 }}>virtual fingerprint timeout</div>
        </div>
      </div>
    )
  }

  if (attackId === 'double_vote') {
    return (
      <div className="atk-chip" style={{ marginBottom: 14 }}>
        <div style={{ display: 'grid', gridTemplateColumns: '90px 1fr 90px', gap: 8, color: '#c8a951', fontSize: 10, marginBottom: 8 }}>
          <span>ROW</span><span>NULLIFIER</span><span>INDEX</span>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: '90px 1fr 90px', gap: 8, color: '#8aa1a8', padding: '6px 0', borderTop: '1px solid #26343a' }}>
          <span>existing</span><span className="nullifier-hot">64f30495...98772</span><span>UNIQUE</span>
        </div>
        <div className="incoming-row" style={{ display: 'grid', gridTemplateColumns: '90px 1fr 90px', gap: 8, color: '#ff6b6b', padding: '6px 0', borderTop: '1px solid #26343a' }}>
          <span>new</span><span>64f30495...98772</span><span>REJECT</span>
        </div>
      </div>
    )
  }

  if (attackId === 'fake_shard') {
    return (
      <div className="atk-chip" style={{ height: 150, position: 'relative', marginBottom: 14, overflow: 'hidden' }}>
        <svg viewBox="0 0 500 130" width="100%" height="120">
          <path d="M20 95 C150 15 310 15 480 95" stroke="#8fc8b0" fill="none" strokeWidth="3" />
          <circle cx="330" cy="28" r="8" fill="#ff6b6b" />
          <text x="345" y="32" fill="#ffb3b3" fontSize="13">fake shard</text>
          <text x="32" y="118" fill="#8aa1a8" fontSize="12">Feldman commitment curve</text>
        </svg>
        <div className="radar-beam" style={{ position: 'absolute', top: 0, width: 10, height: '100%', background: 'linear-gradient(90deg, transparent, #8fc8b0, transparent)' }} />
      </div>
    )
  }

  if (attackId === 'merkle_forgery') {
    return (
      <div className="atk-chip" style={{ display: 'grid', gridTemplateColumns: '1fr 80px 1fr', gap: 12, alignItems: 'center', marginBottom: 14 }}>
        <div className="atk-chip">
          <div style={{ color: '#ffb3b3', fontSize: 11 }}>ATTACKER LOCAL TREE</div>
          <div style={{ color: '#ff6b6b', marginTop: 8 }}>root: deadbeef...cafe</div>
        </div>
        <div className="compare-arrow" style={{ textAlign: 'center', color: '#ff6b6b', fontSize: 26 }}>!=</div>
        <div className="atk-chip">
          <div style={{ color: '#8fc8b0', fontSize: 11 }}>PUBLIC BULLETIN BOARD</div>
          <div style={{ color: '#c8a951', marginTop: 8 }}>root: {shortHash(board?.merkle_root)}</div>
        </div>
      </div>
    )
  }

  if (attackId === 'panic_pin') {
    return (
      <div className="atk-chip" style={{ marginBottom: 14 }}>
        <div style={{ color: '#8fc8b0', fontWeight: 700, marginBottom: 8 }}>Success. Vote Recorded.</div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 90px', gap: 10, color: '#8aa1a8', borderTop: '1px solid #26343a', paddingTop: 10 }}>
          <span>votes.is_decoy</span><span className="decoy-mask">1</span>
        </div>
        <div style={{ height: 6, background: '#172126', marginTop: 14 }}>
          <div className="scan-bar" style={{ height: '100%', background: '#c8a951' }} />
        </div>
        <div style={{ color: '#ffb3b3', fontSize: 11, marginTop: 8 }}>reveal scanner: coercion tag skipped</div>
      </div>
    )
  }

  if (attackId === 'dom_hijack') {
    return (
      <div className="atk-chip" style={{ marginBottom: 14, position: 'relative', overflow: 'hidden' }}>
        <div className="malware-banner" style={{ background: '#8a1a1a', color: 'white', padding: 8, borderRadius: 4, marginBottom: 12 }}>
          MALICIOUS SCRIPT INJECTED
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 40px 1fr', gap: 10, alignItems: 'center' }}>
          <div className="atk-chip"><div style={{ color: '#8aa1a8' }}>Selected Candidate</div><div style={{ color: 'white', fontSize: 20 }}>Candidate A</div></div>
          <div style={{ color: '#ff6b6b', textAlign: 'center' }}>--&gt;</div>
          <div className="atk-chip"><div style={{ color: '#8aa1a8' }}>Mutated DOM</div><div className="glitch-text" style={{ color: '#ff6b6b', fontSize: 20 }}>Candidate B</div></div>
        </div>
      </div>
    )
  }

  if (attackId === 'db_tamper') {
    return (
      <div className="atk-chip" style={{ marginBottom: 14 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 12 }}>
          <span style={{ color: '#8aa1a8' }}>health status</span>
          <span className="tamper-badge" style={{ padding: '4px 8px', borderRadius: 4 }}>TAMPER DETECTED</span>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8, alignItems: 'center' }}>
          <div className="atk-chip" style={{ textAlign: 'center' }}>leaf #4</div>
          <div className="snap-line" style={{ height: 4 }} />
          <div className="atk-chip" style={{ textAlign: 'center', color: '#ff6b6b' }}>root mismatch</div>
        </div>
      </div>
    )
  }

  return (
    <div className="atk-chip" style={{ marginBottom: 14, color: '#8aa1a8', lineHeight: 1.6 }}>
      This scenario highlights a residual risk. Run it to populate the console and defense roadmap.
    </div>
  )
}

export default function AttackLab() {
  const [selected, setSelected] = useState(ATTACKS[0].id)
  const [rollNo, setRollNo] = useState('')
  const [pin, setPin] = useState('')
  const [allowLiveProbe, setAllowLiveProbe] = useState(false)
  const [board, setBoard] = useState(null)
  const [result, setResult] = useState(null)
  const [terminal, setTerminal] = useState(['boot attacker console', 'load secure-vote profile', 'awaiting scenario'])
  const [audit, setAudit] = useState([
    { time: now(), level: 'INFO', text: 'Attack Lab initialized in educational mode.' },
    { time: now(), level: 'INFO', text: 'No production exploit code will be executed.' }
  ])
  const [loading, setLoading] = useState(false)
  const [activeTab, setActiveTab] = useState('flow')
  const [error, setError] = useState('')
  const [runId, setRunId] = useState(0)

  const attack = useMemo(() => ATTACKS.find(item => item.id === selected), [selected])

  useEffect(() => {
    api.get('/election/root')
      .then(({ data }) => setBoard(data))
      .catch(() => setBoard({ merkle_root: null, total_votes: 0, status: 'offline' }))
  }, [result])

  const appendAudit = (level, text) => {
    setAudit(items => [{ time: now(), level, text }, ...items].slice(0, 10))
  }

  const runAttack = async () => {
    setLoading(true)
    setError('')
    setResult(null)
    setRunId(value => value + 1)

    const baseLines = [
      `select attack --id ${attack.id}`,
      ...attack.commands,
      'stream defense telemetry'
    ]
    setTerminal(baseLines.map(line => `$ ${line}`))
    appendAudit('WARN', `${attack.title} simulation started.`)

    try {
      let data
      if (attack.backend) {
        const response = await api.post('/attack/run', {
          scenario_id: attack.backend,
          roll_no: rollNo || null,
          pin: pin || null,
          allow_live_probe: allowLiveProbe
        })
        data = response.data
      } else {
        data = {
          verdict: attack.status === 'defended' ? 'defended' : attack.status,
          summary: attack.limitation,
          events: [
            { status: 'attack', title: 'Payload staged', detail: attack.short },
            { status: attack.status === 'defended' ? 'blocked' : 'observed', title: 'System response', detail: attack.defense },
            { status: attack.status === 'defended' ? 'defended' : 'failed', title: 'Residual risk', detail: attack.limitation }
          ]
        }
      }

      setResult(data)
      setTerminal(lines => [
        ...lines,
        ...attackExtraLines(attack.id),
        `> verdict=${data.verdict}`,
        `> summary="${data.summary}"`,
        '> simulation complete'
      ])
      appendAudit(data.verdict === 'defended' ? 'PASS' : 'RISK', data.summary)
      if (attackAuditLine(attack.id)) {
        appendAudit(attack.status === 'partially exposed' ? 'RISK' : 'WARN', attackAuditLine(attack.id))
      }
    } catch (err) {
      const detail = err.response?.data?.detail || err.message
      setError(detail)
      setTerminal(lines => [...lines, `! ${detail}`])
      appendAudit('ERR', detail)
    }
    setLoading(false)
  }

  const dummyRows = [
    {
      id: 'latest',
      nullifier: result?.scenario_id === 'double_vote' ? 'duplicate blocked' : 'b3f4d10a...',
      aes_key: 'wrapped:x25519',
      is_decoy: selected === 'panic_pin' ? '1 possible' : '0',
      merkle_leaf: shortHash(board?.merkle_root),
      timestamp: board?.published_at || 'live'
    },
    {
      id: 'board',
      nullifier: 'not public',
      aes_key: 'not public',
      is_decoy: 'hidden',
      merkle_leaf: `${board?.total_votes ?? 0} votes`,
      timestamp: board?.status || 'loading'
    }
  ]

  const panelText = {
    flow: [
      ['Attack surface', attack.short],
      ['Payload', attack.payload.join(' | ')],
      ['Operator commands', attack.commands.join(' -> ')]
    ],
    defense: [
      ['Current defense', attack.defense],
      ['Runtime result', result?.summary || 'Run the simulation to collect local telemetry.']
    ],
    failure: [
      ['Known limitation', attack.limitation],
      ['Honest note', attack.status === 'defended' ? 'This attack is currently blocked in the demo pipeline.' : 'This remains a design risk or partial exposure.']
    ],
    future: [
      ['Future work', attack.future],
      ['Architecture direction', 'Move trust anchors outside the single server where needed: transparency logs, mix nets, independent root witnesses, and hardware-derived secrets.']
    ]
  }[activeTab]

  return (
    <div style={{ minHeight: '100vh', background: '#070a0d', color: '#d7e2dc', padding: 28, fontFamily: 'monospace' }}>
      <style>{THEATER_CSS}</style>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 18, border: '1px solid #26343a', padding: '12px 16px', borderRadius: 6, background: '#10161a' }}>
        <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#e24b4a' }} />
        <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#ef9f27' }} />
        <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#639922' }} />
        <span style={{ flex: 1, textAlign: 'center', color: '#8aa1a8', fontSize: 12 }}>secure-vote attacker dashboard</span>
        <span style={{ color: '#ffb3b3', border: '1px solid #8a1a1a', padding: '3px 8px', borderRadius: 4, fontSize: 11 }}>EDUCATIONAL SANDBOX</span>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '280px 1.15fr 0.85fr', gap: 16, alignItems: 'start' }}>
        <div>
          <div style={{ color: '#8aa1a8', fontSize: 11, letterSpacing: 2, marginBottom: 10 }}>ATTACK VECTORS</div>
          {ATTACKS.map(item => (
            <button
              key={item.id}
              onClick={() => {
                setSelected(item.id)
                setResult(null)
                setError('')
              }}
              style={{
                width: '100%',
                textAlign: 'left',
                border: `1px solid ${selected === item.id ? SEVERITY_COLOR[item.severity] : '#26343a'}`,
                borderLeft: `4px solid ${SEVERITY_COLOR[item.severity]}`,
                borderRadius: 6,
                background: selected === item.id ? '#1b1717' : '#10161a',
                color: '#d7e2dc',
                padding: 12,
                marginBottom: 8,
                cursor: 'pointer'
              }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', gap: 10, marginBottom: 8 }}>
                <span style={{ color: SEVERITY_COLOR[item.severity], fontSize: 10 }}>{item.severity.toUpperCase()}</span>
                <span style={{ color: VERDICT_COLOR[item.status] || '#8aa1a8', fontSize: 10 }}>{item.status.toUpperCase()}</span>
              </div>
              <div style={{ fontWeight: 700, fontSize: 13 }}>{item.title}</div>
              <div style={{ color: '#8aa1a8', fontSize: 11, lineHeight: 1.45, marginTop: 5 }}>{item.target}</div>
            </button>
          ))}
        </div>

        <div>
          <div style={{ border: '1px solid #26343a', borderRadius: 6, overflow: 'hidden', background: '#0c1114', marginBottom: 16 }}>
            <div style={{ background: '#10161a', borderBottom: '1px solid #26343a', padding: '10px 14px', color: '#8aa1a8', fontSize: 11, letterSpacing: 2 }}>
              LIVE TERMINAL
            </div>
            <div style={{ padding: 16, minHeight: 238 }}>
              <div style={{ color: '#ffb3b3', fontSize: 12, marginBottom: 8 }}>target: {attack.target}</div>
              <div style={{ color: '#d7e2dc', fontSize: 24, fontFamily: 'Georgia, serif', fontWeight: 700, marginBottom: 10 }}>{attack.title}</div>
              <div style={{ color: '#8aa1a8', lineHeight: 1.55, fontSize: 13, marginBottom: 18 }}>{attack.short}</div>
              <Theater key={`${selected}-${runId}`} attackId={selected} board={board} />

              {selected === 'credential_stuffing' && (
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 14 }}>
                  <input
                    value={rollNo}
                    onChange={e => setRollNo(e.target.value)}
                    placeholder="roll number"
                    autoComplete="off"
                    style={{ background: '#070a0d', color: '#d7e2dc', border: '1px solid #26343a', borderRadius: 4, padding: 10 }}
                  />
                  <input
                    value={pin}
                    onChange={e => setPin(e.target.value.replace(/\D/g, '').slice(0, 12))}
                    placeholder="leaked PIN"
                    type="password"
                    inputMode="numeric"
                    autoComplete="off"
                    data-lpignore="true"
                    style={{ background: '#070a0d', color: '#d7e2dc', border: '1px solid #26343a', borderRadius: 4, padding: 10 }}
                  />
                </div>
              )}

              {attack.backend === 'double_vote' && (
                <label style={{ display: 'flex', alignItems: 'center', gap: 10, color: '#8aa1a8', fontSize: 12, marginBottom: 14 }}>
                  <input type="checkbox" checked={allowLiveProbe} onChange={e => setAllowLiveProbe(e.target.checked)} />
                  allow live duplicate insert probe
                </label>
              )}

              <button
                onClick={runAttack}
                disabled={loading}
                style={{ width: '100%', border: 'none', borderRadius: 6, background: '#8a1a1a', color: 'white', padding: 14, letterSpacing: 2, fontFamily: 'monospace', cursor: loading ? 'default' : 'pointer' }}
              >
                {loading ? 'RUNNING ATTACK...' : 'EXECUTE SIMULATION'}
              </button>
              {error && <div style={{ color: '#ff6b6b', marginTop: 12, fontSize: 12 }}>{error}</div>}
            </div>
          </div>

          <div style={{ border: '1px solid #26343a', borderRadius: 6, background: '#0c1114', overflow: 'hidden' }}>
            <div style={{ background: '#10161a', borderBottom: '1px solid #26343a', padding: '10px 14px', color: '#8aa1a8', fontSize: 11, letterSpacing: 2 }}>
              DUMMY SHELL
            </div>
            <div style={{ padding: 14, minHeight: 190 }}>
              {terminal.map((line, i) => (
                <div key={i} style={{ color: line.startsWith('!') ? '#ff6b6b' : line.startsWith('>') ? '#c8a951' : '#8fc8b0', fontSize: 12, lineHeight: 1.7 }}>
                  {line}
                </div>
              ))}
            </div>
          </div>
        </div>

        <div>
          <div style={{ border: '1px solid #26343a', borderRadius: 6, background: '#0c1114', overflow: 'hidden', marginBottom: 16 }}>
            <div style={{ background: '#10161a', borderBottom: '1px solid #26343a', padding: '10px 14px', color: '#8aa1a8', fontSize: 11, letterSpacing: 2 }}>
              DUMMY LIVE DATABASE
            </div>
            <div style={{ padding: 12, overflowX: 'auto' }}>
              <div style={{ display: 'grid', gridTemplateColumns: '60px 120px 120px 80px 120px 120px', gap: 8, color: '#c8a951', fontSize: 10, marginBottom: 8 }}>
                {DB_COLUMNS.map(col => <div key={col}>{col}</div>)}
              </div>
              {dummyRows.map((row, i) => (
                <div key={i} style={{ display: 'grid', gridTemplateColumns: '60px 120px 120px 80px 120px 120px', gap: 8, color: '#8aa1a8', fontSize: 10, padding: '7px 0', borderTop: '1px solid #1b252a' }}>
                  {DB_COLUMNS.map(col => <div key={col} style={{ overflow: 'hidden', textOverflow: 'ellipsis' }}>{row[col]}</div>)}
                </div>
              ))}
            </div>
          </div>

          <div style={{ border: '1px solid #26343a', borderRadius: 6, background: '#0c1114', overflow: 'hidden' }}>
            <div style={{ background: '#10161a', borderBottom: '1px solid #26343a', padding: '10px 14px', color: '#8aa1a8', fontSize: 11, letterSpacing: 2 }}>
              DUMMY AUDIT LOG
            </div>
            <div style={{ padding: 12, minHeight: 220 }}>
              {audit.map((item, i) => (
                <div key={i} style={{ display: 'grid', gridTemplateColumns: '80px 54px 1fr', gap: 8, padding: '8px 0', borderBottom: '1px solid #1b252a', fontSize: 11 }}>
                  <span style={{ color: '#5a8fa8' }}>{item.time}</span>
                  <span style={{ color: item.level === 'PASS' ? '#8fc8b0' : item.level === 'RISK' || item.level === 'WARN' ? '#c8a951' : item.level === 'ERR' ? '#ff6b6b' : '#8aa1a8' }}>{item.level}</span>
                  <span style={{ color: '#8aa1a8' }}>{item.text}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      <div style={{ marginTop: 16, border: '1px solid #26343a', borderRadius: 6, background: '#0c1114', overflow: 'hidden' }}>
        <div style={{ display: 'flex', background: '#10161a', borderBottom: '1px solid #26343a' }}>
          {['flow', 'defense', 'failure', 'future'].map(tab => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              style={{
                padding: '12px 18px',
                background: activeTab === tab ? '#172126' : 'transparent',
                color: activeTab === tab ? '#d7e2dc' : '#8aa1a8',
                border: 'none',
                borderBottom: `2px solid ${activeTab === tab ? '#8a1a1a' : 'transparent'}`,
                cursor: 'pointer',
                fontFamily: 'monospace',
                letterSpacing: 1,
                fontSize: 12
              }}
            >
              {tab.toUpperCase()}
            </button>
          ))}
        </div>
        <div style={{ padding: 18, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
          {panelText.map(([label, text]) => (
            <div key={label} style={{ border: '1px solid #26343a', borderRadius: 6, padding: 16, background: '#070a0d' }}>
              <div style={{ color: '#c8a951', fontSize: 11, letterSpacing: 2, marginBottom: 8 }}>{label.toUpperCase()}</div>
              <div style={{ color: '#8aa1a8', fontSize: 13, lineHeight: 1.65 }}>{text}</div>
            </div>
          ))}
          {result?.events?.map((event, i) => (
            <div key={`${event.title}-${i}`} style={{ border: '1px solid #26343a', borderRadius: 6, padding: 16, background: '#070a0d' }}>
              <div style={{ color: VERDICT_COLOR[event.status] || '#c8a951', fontSize: 11, letterSpacing: 2, marginBottom: 8 }}>{event.status.toUpperCase()}</div>
              <div style={{ color: '#d7e2dc', fontWeight: 700, marginBottom: 6 }}>{event.title}</div>
              <div style={{ color: '#8aa1a8', fontSize: 13, lineHeight: 1.65 }}>{event.detail}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
